AS=wla-65816
LD=wlalink
ROM=fe3

COBJ=game.obj

all: $(ROM).sfc

$(COBJ): src/main.s lists descriptions arena shop dialogues
	$(AS) -I src -I bin -I text/dialogues -I text/lists -I text/arena -I text/shop -x -v -o $@ $<

# need makefile magic to avoid having to list all files manually
lists:
	fe3-text text/lists/chapters.json compile list text/lists/chapters.gen.asm
	fe3-text text/lists/characters.json compile list text/lists/characters.gen.asm
	fe3-text text/lists/classes.json compile list text/lists/classes.gen.asm
	fe3-text text/lists/items.json compile list text/lists/items.gen.asm
	fe3-text text/lists/debug_objectives.json compile list text/lists/debug_objectives.gen.asm
	fe3-text text/lists/teams.json compile list text/lists/teams.gen.asm
	fe3-text text/lists/textboxes.json compile list text/lists/textboxes.gen.asm
	fe3-text text/lists/messages.json compile list text/lists/messages.gen.asm
	fe3-text text/lists/terrain_messages.json compile list text/lists/terrain_messages.gen.asm
	fe3-text text/lists/the_door_opened.json compile list text/lists/the_door_opened.gen.asm
	fe3-text text/lists/menu_unk.json compile list text/lists/menu_unk.gen.asm
	fe3-text text/lists/menu_ingame.json compile list text/lists/menu_ingame.gen.asm
	fe3-text text/lists/menu_inventory.json compile list text/lists/menu_inventory.gen.asm
	fe3-text text/lists/menu_actions.json compile list text/lists/menu_actions.gen.asm
	fe3-text text/lists/menu_items.json compile list text/lists/menu_items.gen.asm
	fe3-text text/lists/menu_unit_profile.json compile list text/lists/menu_unit_profile.gen.asm
	fe3-text text/lists/menu_convoy_errors.json compile list text/lists/menu_convoy_errors.gen.asm
	fe3-text text/lists/units_msg.json compile list text/lists/units_msg.gen.asm
	fe3-text text/lists/menu_unit_unk.json compile list text/lists/menu_unit_unk.gen.asm
	fe3-text text/lists/small_menus.json compile list text/lists/small_menus.gen.asm
	fe3-text text/lists/menu_settings.json compile list text/lists/menu_settings.gen.asm
	fe3-text text/lists/menu_battle_animations.json compile list text/lists/menu_battle_animations.gen.asm
	fe3-text text/lists/empty_menus.json compile list text/lists/empty_menus.gen.asm
	fe3-text text/lists/receive_deposit_throw_away.json compile list text/lists/receive_deposit_throw_away.gen.asm
	fe3-text text/lists/debug_strings.json compile list text/lists/debug_strings.gen.asm
	fe3-text text/lists/menu_preparation.json compile list text/lists/menu_preparation.gen.asm
	fe3-text text/lists/knight_names.json compile list text/lists/knight_names.gen.asm
	fe3-text text/lists/actions_messages.json compile list text/lists/actions_messages.gen.asm
	fe3-text text/lists/unk_names.json compile list text/lists/unk_names.gen.asm

descriptions:
	fe3-text text/descriptions/knight.txt compile dialogue text/descriptions/knight.bin
	fe3-text text/descriptions/thief.txt compile dialogue text/descriptions/thief.bin
	fe3-text text/descriptions/fighter.txt compile dialogue text/descriptions/fighter.bin
	fe3-text text/descriptions/hunter.txt compile dialogue text/descriptions/hunter.bin
	fe3-text text/descriptions/archer.txt compile dialogue text/descriptions/archer.bin
	fe3-text text/descriptions/sniper.txt compile dialogue text/descriptions/sniper.bin
	fe3-text text/descriptions/horseman.txt compile dialogue text/descriptions/horseman.bin
	fe3-text text/descriptions/cavalier.txt compile dialogue text/descriptions/cavalier.bin
	fe3-text text/descriptions/paladin.txt compile dialogue text/descriptions/paladin.bin
	fe3-text text/descriptions/pegasus_knight.txt compile dialogue text/descriptions/pegasus_knight.bin
	fe3-text text/descriptions/dracoknight.txt compile dialogue text/descriptions/dracoknight.bin
	fe3-text text/descriptions/manakete.txt compile dialogue text/descriptions/manakete.bin
	fe3-text text/descriptions/mercenary.txt compile dialogue text/descriptions/mercenary.bin
	fe3-text text/descriptions/freelancer.txt compile dialogue text/descriptions/freelancer.bin
	fe3-text text/descriptions/cleric.txt compile dialogue text/descriptions/cleric.bin
	fe3-text text/descriptions/mage.txt compile dialogue text/descriptions/mage.bin
	fe3-text text/descriptions/bishop.txt compile dialogue text/descriptions/bishop.bin
	fe3-text text/descriptions/hero.txt compile dialogue text/descriptions/hero.bin
	fe3-text text/descriptions/armour_knight.txt compile dialogue text/descriptions/armour_knight.bin
	fe3-text text/descriptions/lord.txt compile dialogue text/descriptions/lord.bin
	fe3-text text/descriptions/general.txt compile dialogue text/descriptions/general.bin
	fe3-text text/descriptions/dancer.txt compile dialogue text/descriptions/dancer.bin

arena:
	fe3-text text/arena/L8E801E.txt compile dialogue text/arena/L8E801E.bin
	fe3-text text/arena/L8E804E.txt compile dialogue text/arena/L8E804E.bin
	fe3-text text/arena/L8E806D.txt compile dialogue text/arena/L8E806D.bin
	fe3-text text/arena/L8E80F9.txt compile dialogue text/arena/L8E80F9.bin
	fe3-text text/arena/L8E810F.txt compile dialogue text/arena/L8E810F.bin
	fe3-text text/arena/L8E813E.txt compile dialogue text/arena/L8E813E.bin
	fe3-text text/arena/L8E8164.txt compile dialogue text/arena/L8E8164.bin
	fe3-text text/arena/L8E8183.txt compile dialogue text/arena/L8E8183.bin
	fe3-text text/arena/L8E81A2.txt compile dialogue text/arena/L8E81A2.bin
	fe3-text text/arena/L8E81C0.txt compile dialogue text/arena/L8E81C0.bin

shop:
	fe3-text text/shop/L8E8293.txt compile dialogue text/shop/L8E8293.bin
	fe3-text text/shop/L8E82AC.txt compile dialogue text/shop/L8E82AC.bin
	fe3-text text/shop/L8E82B8.txt compile dialogue text/shop/L8E82B8.bin
	fe3-text text/shop/L8E82C5.txt compile dialogue text/shop/L8E82C5.bin
	fe3-text text/shop/L8E82D7.txt compile dialogue text/shop/L8E82D7.bin
	fe3-text text/shop/L8E82E7.txt compile dialogue text/shop/L8E82E7.bin
	fe3-text text/shop/L8E82F3.txt compile dialogue text/shop/L8E82F3.bin
	fe3-text text/shop/L8E8301.txt compile dialogue text/shop/L8E8301.bin
	fe3-text text/shop/L8E831F.txt compile dialogue text/shop/L8E831F.bin
	fe3-text text/shop/L8E8343.txt compile dialogue text/shop/L8E8343.bin
	fe3-text text/shop/L8E8355.txt compile dialogue text/shop/L8E8355.bin
	fe3-text text/shop/L8E8364.txt compile dialogue text/shop/L8E8364.bin
	fe3-text text/shop/L8E8374.txt compile dialogue text/shop/L8E8374.bin
	fe3-text text/shop/L8E838A.txt compile dialogue text/shop/L8E838A.bin
	fe3-text text/shop/L8E8395.txt compile dialogue text/shop/L8E8395.bin
	fe3-text text/shop/L8E83A6.txt compile dialogue text/shop/L8E83A6.bin
	fe3-text text/shop/L8E83B6.txt compile dialogue text/shop/L8E83B6.bin
	fe3-text text/shop/L8E83C9.txt compile dialogue text/shop/L8E83C9.bin
	fe3-text text/shop/L8E83DD.txt compile dialogue text/shop/L8E83DD.bin
	fe3-text text/shop/L8E8401.txt compile dialogue text/shop/L8E8401.bin
	fe3-text text/shop/L8E8422.txt compile dialogue text/shop/L8E8422.bin
	fe3-text text/shop/L8E843D.txt compile dialogue text/shop/L8E843D.bin
	fe3-text text/shop/L8E844E.txt compile dialogue text/shop/L8E844E.bin
	fe3-text text/shop/L8E8466.txt compile dialogue text/shop/L8E8466.bin
	fe3-text text/shop/L8E847D.txt compile dialogue text/shop/L8E847D.bin
	fe3-text text/shop/L8E848C.txt compile dialogue text/shop/L8E848C.bin
	fe3-text text/shop/L8E8498.txt compile dialogue text/shop/L8E8498.bin
	fe3-text text/shop/L8E84A9.txt compile dialogue text/shop/L8E84A9.bin
	fe3-text text/shop/L8E84B7.txt compile dialogue text/shop/L8E84B7.bin
	fe3-text text/shop/L8E84C3.txt compile dialogue text/shop/L8E84C3.bin
	fe3-text text/shop/L8E84D4.txt compile dialogue text/shop/L8E84D4.bin
	fe3-text text/shop/L8E84F2.txt compile dialogue text/shop/L8E84F2.bin
	fe3-text text/shop/L8E8517.txt compile dialogue text/shop/L8E8517.bin
	fe3-text text/shop/L8E852D.txt compile dialogue text/shop/L8E852D.bin
	fe3-text text/shop/L8E853E.txt compile dialogue text/shop/L8E853E.bin
	fe3-text text/shop/L8E854D.txt compile dialogue text/shop/L8E854D.bin
	fe3-text text/shop/L8E8564.txt compile dialogue text/shop/L8E8564.bin
	fe3-text text/shop/L8E8570.txt compile dialogue text/shop/L8E8570.bin
	fe3-text text/shop/L8E8582.txt compile dialogue text/shop/L8E8582.bin
	fe3-text text/shop/L8E8595.txt compile dialogue text/shop/L8E8595.bin
	fe3-text text/shop/L8E85A9.txt compile dialogue text/shop/L8E85A9.bin
	fe3-text text/shop/L8E85BC.txt compile dialogue text/shop/L8E85BC.bin
	fe3-text text/shop/L8E85DF.txt compile dialogue text/shop/L8E85DF.bin
	fe3-text text/shop/L8E85FE.txt compile dialogue text/shop/L8E85FE.bin
	fe3-text text/shop/L8E8619.txt compile dialogue text/shop/L8E8619.bin
	fe3-text text/shop/L8E862C.txt compile dialogue text/shop/L8E862C.bin
	fe3-text text/shop/L8E8643.txt compile dialogue text/shop/L8E8643.bin

dialogues:
	fe3-text text/dialogues/dialogue001.txt compile dialogue text/dialogues/dialogue001.bin
	fe3-text text/dialogues/dialogue002.txt compile dialogue text/dialogues/dialogue002.bin
	fe3-text text/dialogues/dialogue003.txt compile dialogue text/dialogues/dialogue003.bin
	fe3-text text/dialogues/dialogue004.txt compile dialogue text/dialogues/dialogue004.bin
	fe3-text text/dialogues/dialogue005.txt compile dialogue text/dialogues/dialogue005.bin
	fe3-text text/dialogues/dialogue006.txt compile dialogue text/dialogues/dialogue006.bin
	fe3-text text/dialogues/dialogue007.txt compile dialogue text/dialogues/dialogue007.bin
	fe3-text text/dialogues/dialogue008.txt compile dialogue text/dialogues/dialogue008.bin
	fe3-text text/dialogues/dialogue009.txt compile dialogue text/dialogues/dialogue009.bin
	fe3-text text/dialogues/dialogue010.txt compile dialogue text/dialogues/dialogue010.bin
	fe3-text text/dialogues/dialogue011.txt compile dialogue text/dialogues/dialogue011.bin
	fe3-text text/dialogues/dialogue012.txt compile dialogue text/dialogues/dialogue012.bin
	fe3-text text/dialogues/dialogue013.txt compile dialogue text/dialogues/dialogue013.bin
	fe3-text text/dialogues/dialogue014.txt compile dialogue text/dialogues/dialogue014.bin
	fe3-text text/dialogues/dialogue015.txt compile dialogue text/dialogues/dialogue015.bin
	fe3-text text/dialogues/dialogue016.txt compile dialogue text/dialogues/dialogue016.bin
	fe3-text text/dialogues/dialogue017.txt compile dialogue text/dialogues/dialogue017.bin
	fe3-text text/dialogues/dialogue018.txt compile dialogue text/dialogues/dialogue018.bin
	fe3-text text/dialogues/dialogue019.txt compile dialogue text/dialogues/dialogue019.bin
	fe3-text text/dialogues/dialogue020.txt compile dialogue text/dialogues/dialogue020.bin
	fe3-text text/dialogues/dialogue021.txt compile dialogue text/dialogues/dialogue021.bin
	fe3-text text/dialogues/dialogue022.txt compile dialogue text/dialogues/dialogue022.bin
	fe3-text text/dialogues/dialogue023.txt compile dialogue text/dialogues/dialogue023.bin
	fe3-text text/dialogues/dialogue024.txt compile dialogue text/dialogues/dialogue024.bin
	fe3-text text/dialogues/dialogue025.txt compile dialogue text/dialogues/dialogue025.bin
	fe3-text text/dialogues/dialogue026.txt compile dialogue text/dialogues/dialogue026.bin
	fe3-text text/dialogues/dialogue027.txt compile dialogue text/dialogues/dialogue027.bin
	fe3-text text/dialogues/dialogue028.txt compile dialogue text/dialogues/dialogue028.bin
	fe3-text text/dialogues/dialogue029.txt compile dialogue text/dialogues/dialogue029.bin
	fe3-text text/dialogues/dialogue030.txt compile dialogue text/dialogues/dialogue030.bin
	fe3-text text/dialogues/dialogue031.txt compile dialogue text/dialogues/dialogue031.bin
	fe3-text text/dialogues/dialogue032.txt compile dialogue text/dialogues/dialogue032.bin
	fe3-text text/dialogues/dialogue033.txt compile dialogue text/dialogues/dialogue033.bin
	fe3-text text/dialogues/dialogue034.txt compile dialogue text/dialogues/dialogue034.bin
	fe3-text text/dialogues/dialogue035.txt compile dialogue text/dialogues/dialogue035.bin
	fe3-text text/dialogues/dialogue036.txt compile dialogue text/dialogues/dialogue036.bin
	fe3-text text/dialogues/dialogue037.txt compile dialogue text/dialogues/dialogue037.bin
	fe3-text text/dialogues/dialogue038.txt compile dialogue text/dialogues/dialogue038.bin
	fe3-text text/dialogues/dialogue039.txt compile dialogue text/dialogues/dialogue039.bin
	fe3-text text/dialogues/dialogue040.txt compile dialogue text/dialogues/dialogue040.bin
	fe3-text text/dialogues/dialogue041.txt compile dialogue text/dialogues/dialogue041.bin
	fe3-text text/dialogues/dialogue042.txt compile dialogue text/dialogues/dialogue042.bin
	fe3-text text/dialogues/dialogue043.txt compile dialogue text/dialogues/dialogue043.bin
	fe3-text text/dialogues/dialogue044.txt compile dialogue text/dialogues/dialogue044.bin
	fe3-text text/dialogues/dialogue045.txt compile dialogue text/dialogues/dialogue045.bin
	fe3-text text/dialogues/dialogue046.txt compile dialogue text/dialogues/dialogue046.bin
	fe3-text text/dialogues/dialogue047.txt compile dialogue text/dialogues/dialogue047.bin
	fe3-text text/dialogues/dialogue048.txt compile dialogue text/dialogues/dialogue048.bin
	fe3-text text/dialogues/dialogue049.txt compile dialogue text/dialogues/dialogue049.bin
	fe3-text text/dialogues/dialogue050.txt compile dialogue text/dialogues/dialogue050.bin
	fe3-text text/dialogues/dialogue051.txt compile dialogue text/dialogues/dialogue051.bin
	fe3-text text/dialogues/dialogue052.txt compile dialogue text/dialogues/dialogue052.bin
	fe3-text text/dialogues/dialogue053.txt compile dialogue text/dialogues/dialogue053.bin
	fe3-text text/dialogues/dialogue054.txt compile dialogue text/dialogues/dialogue054.bin
	fe3-text text/dialogues/dialogue055.txt compile dialogue text/dialogues/dialogue055.bin
	fe3-text text/dialogues/dialogue056.txt compile dialogue text/dialogues/dialogue056.bin
	fe3-text text/dialogues/dialogue057.txt compile dialogue text/dialogues/dialogue057.bin
	fe3-text text/dialogues/dialogue058.txt compile dialogue text/dialogues/dialogue058.bin
	fe3-text text/dialogues/dialogue059.txt compile dialogue text/dialogues/dialogue059.bin
	fe3-text text/dialogues/dialogue060.txt compile dialogue text/dialogues/dialogue060.bin
	fe3-text text/dialogues/dialogue061.txt compile dialogue text/dialogues/dialogue061.bin
	fe3-text text/dialogues/dialogue062.txt compile dialogue text/dialogues/dialogue062.bin
	fe3-text text/dialogues/dialogue063.txt compile dialogue text/dialogues/dialogue063.bin
	fe3-text text/dialogues/dialogue064.txt compile dialogue text/dialogues/dialogue064.bin
	fe3-text text/dialogues/dialogue065.txt compile dialogue text/dialogues/dialogue065.bin
	fe3-text text/dialogues/dialogue066.txt compile dialogue text/dialogues/dialogue066.bin
	fe3-text text/dialogues/dialogue067.txt compile dialogue text/dialogues/dialogue067.bin
	fe3-text text/dialogues/dialogue068.txt compile dialogue text/dialogues/dialogue068.bin
	fe3-text text/dialogues/dialogue069.txt compile dialogue text/dialogues/dialogue069.bin
	fe3-text text/dialogues/dialogue070.txt compile dialogue text/dialogues/dialogue070.bin
	fe3-text text/dialogues/dialogue071.txt compile dialogue text/dialogues/dialogue071.bin
	fe3-text text/dialogues/dialogue072.txt compile dialogue text/dialogues/dialogue072.bin
	fe3-text text/dialogues/dialogue073.txt compile dialogue text/dialogues/dialogue073.bin
	fe3-text text/dialogues/dialogue074.txt compile dialogue text/dialogues/dialogue074.bin
	fe3-text text/dialogues/dialogue075.txt compile dialogue text/dialogues/dialogue075.bin
	fe3-text text/dialogues/dialogue076.txt compile dialogue text/dialogues/dialogue076.bin
	fe3-text text/dialogues/dialogue077.txt compile dialogue text/dialogues/dialogue077.bin
	fe3-text text/dialogues/dialogue078.txt compile dialogue text/dialogues/dialogue078.bin
	fe3-text text/dialogues/dialogue079.txt compile dialogue text/dialogues/dialogue079.bin
	fe3-text text/dialogues/dialogue080.txt compile dialogue text/dialogues/dialogue080.bin
	fe3-text text/dialogues/dialogue081.txt compile dialogue text/dialogues/dialogue081.bin
	fe3-text text/dialogues/dialogue082.txt compile dialogue text/dialogues/dialogue082.bin
	fe3-text text/dialogues/dialogue083.txt compile dialogue text/dialogues/dialogue083.bin
	fe3-text text/dialogues/dialogue084.txt compile dialogue text/dialogues/dialogue084.bin
	fe3-text text/dialogues/dialogue085.txt compile dialogue text/dialogues/dialogue085.bin
	fe3-text text/dialogues/dialogue086.txt compile dialogue text/dialogues/dialogue086.bin
	fe3-text text/dialogues/dialogue087.txt compile dialogue text/dialogues/dialogue087.bin
	fe3-text text/dialogues/dialogue088.txt compile dialogue text/dialogues/dialogue088.bin
	fe3-text text/dialogues/dialogue089.txt compile dialogue text/dialogues/dialogue089.bin
	fe3-text text/dialogues/dialogue090.txt compile dialogue text/dialogues/dialogue090.bin
	fe3-text text/dialogues/dialogue091.txt compile dialogue text/dialogues/dialogue091.bin
	fe3-text text/dialogues/dialogue092.txt compile dialogue text/dialogues/dialogue092.bin
	fe3-text text/dialogues/dialogue093.txt compile dialogue text/dialogues/dialogue093.bin
	fe3-text text/dialogues/dialogue094.txt compile dialogue text/dialogues/dialogue094.bin
	fe3-text text/dialogues/dialogue095.txt compile dialogue text/dialogues/dialogue095.bin
	fe3-text text/dialogues/dialogue096.txt compile dialogue text/dialogues/dialogue096.bin
	fe3-text text/dialogues/dialogue097.txt compile dialogue text/dialogues/dialogue097.bin
	fe3-text text/dialogues/dialogue098.txt compile dialogue text/dialogues/dialogue098.bin
	fe3-text text/dialogues/dialogue099.txt compile dialogue text/dialogues/dialogue099.bin
	fe3-text text/dialogues/dialogue100.txt compile dialogue text/dialogues/dialogue100.bin
	fe3-text text/dialogues/dialogue101.txt compile dialogue text/dialogues/dialogue101.bin
	fe3-text text/dialogues/dialogue102.txt compile dialogue text/dialogues/dialogue102.bin
	fe3-text text/dialogues/dialogue103.txt compile dialogue text/dialogues/dialogue103.bin
	fe3-text text/dialogues/dialogue104.txt compile dialogue text/dialogues/dialogue104.bin
	fe3-text text/dialogues/dialogue105.txt compile dialogue text/dialogues/dialogue105.bin
	fe3-text text/dialogues/dialogue106.txt compile dialogue text/dialogues/dialogue106.bin
	fe3-text text/dialogues/dialogue107.txt compile dialogue text/dialogues/dialogue107.bin
	fe3-text text/dialogues/dialogue108.txt compile dialogue text/dialogues/dialogue108.bin
	fe3-text text/dialogues/dialogue109.txt compile dialogue text/dialogues/dialogue109.bin
	fe3-text text/dialogues/dialogue110.txt compile dialogue text/dialogues/dialogue110.bin
	fe3-text text/dialogues/dialogue111.txt compile dialogue text/dialogues/dialogue111.bin
	fe3-text text/dialogues/dialogue112.txt compile dialogue text/dialogues/dialogue112.bin
	fe3-text text/dialogues/dialogue113.txt compile dialogue text/dialogues/dialogue113.bin
	fe3-text text/dialogues/dialogue114.txt compile dialogue text/dialogues/dialogue114.bin
	fe3-text text/dialogues/dialogue115.txt compile dialogue text/dialogues/dialogue115.bin
	fe3-text text/dialogues/dialogue116.txt compile dialogue text/dialogues/dialogue116.bin
	fe3-text text/dialogues/dialogue117.txt compile dialogue text/dialogues/dialogue117.bin
	fe3-text text/dialogues/dialogue118.txt compile dialogue text/dialogues/dialogue118.bin
	fe3-text text/dialogues/dialogue119.txt compile dialogue text/dialogues/dialogue119.bin
	fe3-text text/dialogues/dialogue120.txt compile dialogue text/dialogues/dialogue120.bin
	fe3-text text/dialogues/dialogue121.txt compile dialogue text/dialogues/dialogue121.bin
	fe3-text text/dialogues/dialogue122.txt compile dialogue text/dialogues/dialogue122.bin
	fe3-text text/dialogues/dialogue123.txt compile dialogue text/dialogues/dialogue123.bin
	fe3-text text/dialogues/dialogue124.txt compile dialogue text/dialogues/dialogue124.bin
	fe3-text text/dialogues/dialogue125.txt compile dialogue text/dialogues/dialogue125.bin
	fe3-text text/dialogues/dialogue126.txt compile dialogue text/dialogues/dialogue126.bin
	fe3-text text/dialogues/dialogue127.txt compile dialogue text/dialogues/dialogue127.bin
	fe3-text text/dialogues/dialogue128.txt compile dialogue text/dialogues/dialogue128.bin
	fe3-text text/dialogues/dialogue129.txt compile dialogue text/dialogues/dialogue129.bin
	fe3-text text/dialogues/dialogue130.txt compile dialogue text/dialogues/dialogue130.bin
	fe3-text text/dialogues/dialogue131.txt compile dialogue text/dialogues/dialogue131.bin
	fe3-text text/dialogues/dialogue132.txt compile dialogue text/dialogues/dialogue132.bin
	fe3-text text/dialogues/dialogue133.txt compile dialogue text/dialogues/dialogue133.bin
	fe3-text text/dialogues/dialogue134.txt compile dialogue text/dialogues/dialogue134.bin
	fe3-text text/dialogues/dialogue135.txt compile dialogue text/dialogues/dialogue135.bin
	fe3-text text/dialogues/dialogue136.txt compile dialogue text/dialogues/dialogue136.bin
	fe3-text text/dialogues/dialogue137.txt compile dialogue text/dialogues/dialogue137.bin
	fe3-text text/dialogues/dialogue138.txt compile dialogue text/dialogues/dialogue138.bin
	fe3-text text/dialogues/dialogue139.txt compile dialogue text/dialogues/dialogue139.bin
	fe3-text text/dialogues/dialogue140.txt compile dialogue text/dialogues/dialogue140.bin
	fe3-text text/dialogues/dialogue141.txt compile dialogue text/dialogues/dialogue141.bin
	fe3-text text/dialogues/dialogue142.txt compile dialogue text/dialogues/dialogue142.bin
	fe3-text text/dialogues/dialogue143.txt compile dialogue text/dialogues/dialogue143.bin
	fe3-text text/dialogues/dialogue144.txt compile dialogue text/dialogues/dialogue144.bin
	fe3-text text/dialogues/dialogue145.txt compile dialogue text/dialogues/dialogue145.bin
	fe3-text text/dialogues/dialogue146.txt compile dialogue text/dialogues/dialogue146.bin
	fe3-text text/dialogues/dialogue147.txt compile dialogue text/dialogues/dialogue147.bin
	fe3-text text/dialogues/dialogue148.txt compile dialogue text/dialogues/dialogue148.bin
	fe3-text text/dialogues/dialogue149.txt compile dialogue text/dialogues/dialogue149.bin
	fe3-text text/dialogues/dialogue150.txt compile dialogue text/dialogues/dialogue150.bin
	fe3-text text/dialogues/dialogue151.txt compile dialogue text/dialogues/dialogue151.bin
	fe3-text text/dialogues/dialogue152.txt compile dialogue text/dialogues/dialogue152.bin
	fe3-text text/dialogues/dialogue153.txt compile dialogue text/dialogues/dialogue153.bin
	fe3-text text/dialogues/dialogue154.txt compile dialogue text/dialogues/dialogue154.bin
	fe3-text text/dialogues/dialogue155.txt compile dialogue text/dialogues/dialogue155.bin
	fe3-text text/dialogues/dialogue156.txt compile dialogue text/dialogues/dialogue156.bin
	fe3-text text/dialogues/dialogue157.txt compile dialogue text/dialogues/dialogue157.bin
	fe3-text text/dialogues/dialogue158.txt compile dialogue text/dialogues/dialogue158.bin
	fe3-text text/dialogues/dialogue159.txt compile dialogue text/dialogues/dialogue159.bin
	fe3-text text/dialogues/dialogue160.txt compile dialogue text/dialogues/dialogue160.bin
	fe3-text text/dialogues/dialogue161.txt compile dialogue text/dialogues/dialogue161.bin
	fe3-text text/dialogues/dialogue162.txt compile dialogue text/dialogues/dialogue162.bin
	fe3-text text/dialogues/dialogue163.txt compile dialogue text/dialogues/dialogue163.bin
	fe3-text text/dialogues/dialogue164.txt compile dialogue text/dialogues/dialogue164.bin
	fe3-text text/dialogues/dialogue165.txt compile dialogue text/dialogues/dialogue165.bin
	fe3-text text/dialogues/dialogue166.txt compile dialogue text/dialogues/dialogue166.bin
	fe3-text text/dialogues/dialogue167.txt compile dialogue text/dialogues/dialogue167.bin
	fe3-text text/dialogues/dialogue168.txt compile dialogue text/dialogues/dialogue168.bin
	fe3-text text/dialogues/dialogue169.txt compile dialogue text/dialogues/dialogue169.bin
	fe3-text text/dialogues/dialogue170.txt compile dialogue text/dialogues/dialogue170.bin
	fe3-text text/dialogues/dialogue171.txt compile dialogue text/dialogues/dialogue171.bin
	fe3-text text/dialogues/dialogue172.txt compile dialogue text/dialogues/dialogue172.bin
	fe3-text text/dialogues/dialogue173.txt compile dialogue text/dialogues/dialogue173.bin
	fe3-text text/dialogues/dialogue174.txt compile dialogue text/dialogues/dialogue174.bin
	fe3-text text/dialogues/dialogue175.txt compile dialogue text/dialogues/dialogue175.bin
	fe3-text text/dialogues/dialogue176.txt compile dialogue text/dialogues/dialogue176.bin
	fe3-text text/dialogues/dialogue177.txt compile dialogue text/dialogues/dialogue177.bin
	fe3-text text/dialogues/dialogue178.txt compile dialogue text/dialogues/dialogue178.bin
	fe3-text text/dialogues/dialogue179.txt compile dialogue text/dialogues/dialogue179.bin
	fe3-text text/dialogues/dialogue180.txt compile dialogue text/dialogues/dialogue180.bin
	fe3-text text/dialogues/dialogue181.txt compile dialogue text/dialogues/dialogue181.bin
	fe3-text text/dialogues/dialogue182.txt compile dialogue text/dialogues/dialogue182.bin
	fe3-text text/dialogues/dialogue183.txt compile dialogue text/dialogues/dialogue183.bin
	fe3-text text/dialogues/dialogue184.txt compile dialogue text/dialogues/dialogue184.bin
	fe3-text text/dialogues/dialogue185.txt compile dialogue text/dialogues/dialogue185.bin
	fe3-text text/dialogues/dialogue186.txt compile dialogue text/dialogues/dialogue186.bin
	fe3-text text/dialogues/dialogue187.txt compile dialogue text/dialogues/dialogue187.bin
	fe3-text text/dialogues/dialogue188.txt compile dialogue text/dialogues/dialogue188.bin
	fe3-text text/dialogues/dialogue189.txt compile dialogue text/dialogues/dialogue189.bin
	fe3-text text/dialogues/dialogue190.txt compile dialogue text/dialogues/dialogue190.bin
	fe3-text text/dialogues/dialogue191.txt compile dialogue text/dialogues/dialogue191.bin
	fe3-text text/dialogues/dialogue192.txt compile dialogue text/dialogues/dialogue192.bin
	fe3-text text/dialogues/dialogue193.txt compile dialogue text/dialogues/dialogue193.bin
	fe3-text text/dialogues/dialogue194.txt compile dialogue text/dialogues/dialogue194.bin
	fe3-text text/dialogues/dialogue195.txt compile dialogue text/dialogues/dialogue195.bin
	fe3-text text/dialogues/dialogue196.txt compile dialogue text/dialogues/dialogue196.bin
	fe3-text text/dialogues/dialogue197.txt compile dialogue text/dialogues/dialogue197.bin
	fe3-text text/dialogues/dialogue198.txt compile dialogue text/dialogues/dialogue198.bin
	fe3-text text/dialogues/dialogue199.txt compile dialogue text/dialogues/dialogue199.bin
	fe3-text text/dialogues/dialogue200.txt compile dialogue text/dialogues/dialogue200.bin
	fe3-text text/dialogues/dialogue201.txt compile dialogue text/dialogues/dialogue201.bin
	fe3-text text/dialogues/dialogue202.txt compile dialogue text/dialogues/dialogue202.bin
	fe3-text text/dialogues/dialogue203.txt compile dialogue text/dialogues/dialogue203.bin
	fe3-text text/dialogues/dialogue204.txt compile dialogue text/dialogues/dialogue204.bin
	fe3-text text/dialogues/dialogue205.txt compile dialogue text/dialogues/dialogue205.bin
	fe3-text text/dialogues/dialogue206.txt compile dialogue text/dialogues/dialogue206.bin
	fe3-text text/dialogues/dialogue207.txt compile dialogue text/dialogues/dialogue207.bin
	fe3-text text/dialogues/dialogue208.txt compile dialogue text/dialogues/dialogue208.bin
	fe3-text text/dialogues/dialogue209.txt compile dialogue text/dialogues/dialogue209.bin
	fe3-text text/dialogues/dialogue210.txt compile dialogue text/dialogues/dialogue210.bin
	fe3-text text/dialogues/dialogue211.txt compile dialogue text/dialogues/dialogue211.bin
	fe3-text text/dialogues/dialogue212.txt compile dialogue text/dialogues/dialogue212.bin
	fe3-text text/dialogues/dialogue213.txt compile dialogue text/dialogues/dialogue213.bin
	fe3-text text/dialogues/dialogue214.txt compile dialogue text/dialogues/dialogue214.bin
	fe3-text text/dialogues/dialogue215.txt compile dialogue text/dialogues/dialogue215.bin
	fe3-text text/dialogues/dialogue216.txt compile dialogue text/dialogues/dialogue216.bin
	fe3-text text/dialogues/dialogue217.txt compile dialogue text/dialogues/dialogue217.bin
	fe3-text text/dialogues/dialogue218.txt compile dialogue text/dialogues/dialogue218.bin
	fe3-text text/dialogues/dialogue219.txt compile dialogue text/dialogues/dialogue219.bin
	fe3-text text/dialogues/dialogue220.txt compile dialogue text/dialogues/dialogue220.bin
	fe3-text text/dialogues/dialogue221.txt compile dialogue text/dialogues/dialogue221.bin
	fe3-text text/dialogues/dialogue222.txt compile dialogue text/dialogues/dialogue222.bin
	fe3-text text/dialogues/dialogue223.txt compile dialogue text/dialogues/dialogue223.bin
	fe3-text text/dialogues/dialogue224.txt compile dialogue text/dialogues/dialogue224.bin
	fe3-text text/dialogues/dialogue225.txt compile dialogue text/dialogues/dialogue225.bin
	fe3-text text/dialogues/dialogue226.txt compile dialogue text/dialogues/dialogue226.bin
	fe3-text text/dialogues/dialogue227.txt compile dialogue text/dialogues/dialogue227.bin
	fe3-text text/dialogues/dialogue228.txt compile dialogue text/dialogues/dialogue228.bin
	fe3-text text/dialogues/dialogue229.txt compile dialogue text/dialogues/dialogue229.bin
	fe3-text text/dialogues/dialogue230.txt compile dialogue text/dialogues/dialogue230.bin
	fe3-text text/dialogues/dialogue231.txt compile dialogue text/dialogues/dialogue231.bin
	fe3-text text/dialogues/dialogue232.txt compile dialogue text/dialogues/dialogue232.bin
	fe3-text text/dialogues/dialogue233.txt compile dialogue text/dialogues/dialogue233.bin
	fe3-text text/dialogues/dialogue234.txt compile dialogue text/dialogues/dialogue234.bin
	fe3-text text/dialogues/dialogue235.txt compile dialogue text/dialogues/dialogue235.bin
	fe3-text text/dialogues/dialogue236.txt compile dialogue text/dialogues/dialogue236.bin
	fe3-text text/dialogues/dialogue237.txt compile dialogue text/dialogues/dialogue237.bin
	fe3-text text/dialogues/dialogue238.txt compile dialogue text/dialogues/dialogue238.bin
	fe3-text text/dialogues/dialogue239.txt compile dialogue text/dialogues/dialogue239.bin
	fe3-text text/dialogues/dialogue240.txt compile dialogue text/dialogues/dialogue240.bin
	fe3-text text/dialogues/dialogue241.txt compile dialogue text/dialogues/dialogue241.bin
	fe3-text text/dialogues/dialogue242.txt compile dialogue text/dialogues/dialogue242.bin
	fe3-text text/dialogues/dialogue243.txt compile dialogue text/dialogues/dialogue243.bin
	fe3-text text/dialogues/dialogue244.txt compile dialogue text/dialogues/dialogue244.bin
	fe3-text text/dialogues/dialogue245.txt compile dialogue text/dialogues/dialogue245.bin
	fe3-text text/dialogues/dialogue246.txt compile dialogue text/dialogues/dialogue246.bin
	fe3-text text/dialogues/dialogue247.txt compile dialogue text/dialogues/dialogue247.bin
	fe3-text text/dialogues/dialogue248.txt compile dialogue text/dialogues/dialogue248.bin
	fe3-text text/dialogues/dialogue249.txt compile dialogue text/dialogues/dialogue249.bin
	fe3-text text/dialogues/dialogue250.txt compile dialogue text/dialogues/dialogue250.bin
	fe3-text text/dialogues/dialogue251.txt compile dialogue text/dialogues/dialogue251.bin
	fe3-text text/dialogues/dialogue252.txt compile dialogue text/dialogues/dialogue252.bin
	fe3-text text/dialogues/dialogue253.txt compile dialogue text/dialogues/dialogue253.bin
	fe3-text text/dialogues/dialogue254.txt compile dialogue text/dialogues/dialogue254.bin
	fe3-text text/dialogues/dialogue255.txt compile dialogue text/dialogues/dialogue255.bin
	fe3-text text/dialogues/dialogue256.txt compile dialogue text/dialogues/dialogue256.bin
	fe3-text text/dialogues/dialogue257.txt compile dialogue text/dialogues/dialogue257.bin
	fe3-text text/dialogues/dialogue258.txt compile dialogue text/dialogues/dialogue258.bin
	fe3-text text/dialogues/dialogue259.txt compile dialogue text/dialogues/dialogue259.bin
	fe3-text text/dialogues/dialogue260.txt compile dialogue text/dialogues/dialogue260.bin
	fe3-text text/dialogues/dialogue261.txt compile dialogue text/dialogues/dialogue261.bin
	fe3-text text/dialogues/dialogue262.txt compile dialogue text/dialogues/dialogue262.bin
	fe3-text text/dialogues/dialogue263.txt compile dialogue text/dialogues/dialogue263.bin
	fe3-text text/dialogues/dialogue264.txt compile dialogue text/dialogues/dialogue264.bin
	fe3-text text/dialogues/dialogue265.txt compile dialogue text/dialogues/dialogue265.bin
	fe3-text text/dialogues/dialogue266.txt compile dialogue text/dialogues/dialogue266.bin
	fe3-text text/dialogues/dialogue267.txt compile dialogue text/dialogues/dialogue267.bin
	fe3-text text/dialogues/dialogue268.txt compile dialogue text/dialogues/dialogue268.bin
	fe3-text text/dialogues/dialogue269.txt compile dialogue text/dialogues/dialogue269.bin
	fe3-text text/dialogues/dialogue270.txt compile dialogue text/dialogues/dialogue270.bin
	fe3-text text/dialogues/dialogue271.txt compile dialogue text/dialogues/dialogue271.bin
	fe3-text text/dialogues/dialogue272.txt compile dialogue text/dialogues/dialogue272.bin
	fe3-text text/dialogues/dialogue273.txt compile dialogue text/dialogues/dialogue273.bin
	fe3-text text/dialogues/dialogue274.txt compile dialogue text/dialogues/dialogue274.bin
	fe3-text text/dialogues/dialogue275.txt compile dialogue text/dialogues/dialogue275.bin
	fe3-text text/dialogues/dialogue276.txt compile dialogue text/dialogues/dialogue276.bin
	fe3-text text/dialogues/dialogue277.txt compile dialogue text/dialogues/dialogue277.bin
	fe3-text text/dialogues/dialogue278.txt compile dialogue text/dialogues/dialogue278.bin
	fe3-text text/dialogues/dialogue279.txt compile dialogue text/dialogues/dialogue279.bin
	fe3-text text/dialogues/dialogue280.txt compile dialogue text/dialogues/dialogue280.bin
	fe3-text text/dialogues/dialogue281.txt compile dialogue text/dialogues/dialogue281.bin
	fe3-text text/dialogues/dialogue282.txt compile dialogue text/dialogues/dialogue282.bin
	fe3-text text/dialogues/dialogue283.txt compile dialogue text/dialogues/dialogue283.bin
	fe3-text text/dialogues/dialogue284.txt compile dialogue text/dialogues/dialogue284.bin
	fe3-text text/dialogues/dialogue285.txt compile dialogue text/dialogues/dialogue285.bin
	fe3-text text/dialogues/dialogue286.txt compile dialogue text/dialogues/dialogue286.bin
	fe3-text text/dialogues/dialogue287.txt compile dialogue text/dialogues/dialogue287.bin
	fe3-text text/dialogues/dialogue288.txt compile dialogue text/dialogues/dialogue288.bin
	fe3-text text/dialogues/dialogue289.txt compile dialogue text/dialogues/dialogue289.bin
	fe3-text text/dialogues/dialogue290.txt compile dialogue text/dialogues/dialogue290.bin
	fe3-text text/dialogues/dialogue291.txt compile dialogue text/dialogues/dialogue291.bin
	fe3-text text/dialogues/dialogue292.txt compile dialogue text/dialogues/dialogue292.bin
	fe3-text text/dialogues/dialogue293.txt compile dialogue text/dialogues/dialogue293.bin
	fe3-text text/dialogues/dialogue294.txt compile dialogue text/dialogues/dialogue294.bin
	fe3-text text/dialogues/dialogue295.txt compile dialogue text/dialogues/dialogue295.bin
	fe3-text text/dialogues/dialogue296.txt compile dialogue text/dialogues/dialogue296.bin
	fe3-text text/dialogues/dialogue297.txt compile dialogue text/dialogues/dialogue297.bin
	fe3-text text/dialogues/dialogue298.txt compile dialogue text/dialogues/dialogue298.bin
	fe3-text text/dialogues/dialogue299.txt compile dialogue text/dialogues/dialogue299.bin
	fe3-text text/dialogues/dialogue300.txt compile dialogue text/dialogues/dialogue300.bin
	fe3-text text/dialogues/dialogue301.txt compile dialogue text/dialogues/dialogue301.bin
	fe3-text text/dialogues/dialogue302.txt compile dialogue text/dialogues/dialogue302.bin
	fe3-text text/dialogues/dialogue303.txt compile dialogue text/dialogues/dialogue303.bin
	fe3-text text/dialogues/dialogue304.txt compile dialogue text/dialogues/dialogue304.bin
	fe3-text text/dialogues/dialogue305.txt compile dialogue text/dialogues/dialogue305.bin
	fe3-text text/dialogues/dialogue306.txt compile dialogue text/dialogues/dialogue306.bin
	fe3-text text/dialogues/dialogue307.txt compile dialogue text/dialogues/dialogue307.bin
	fe3-text text/dialogues/dialogue308.txt compile dialogue text/dialogues/dialogue308.bin
	fe3-text text/dialogues/dialogue309.txt compile dialogue text/dialogues/dialogue309.bin
	fe3-text text/dialogues/dialogue310.txt compile dialogue text/dialogues/dialogue310.bin
	fe3-text text/dialogues/dialogue311.txt compile dialogue text/dialogues/dialogue311.bin
	fe3-text text/dialogues/dialogue312.txt compile dialogue text/dialogues/dialogue312.bin
	fe3-text text/dialogues/dialogue313.txt compile dialogue text/dialogues/dialogue313.bin
	fe3-text text/dialogues/dialogue314.txt compile dialogue text/dialogues/dialogue314.bin
	fe3-text text/dialogues/dialogue315.txt compile dialogue text/dialogues/dialogue315.bin
	fe3-text text/dialogues/dialogue316.txt compile dialogue text/dialogues/dialogue316.bin
	fe3-text text/dialogues/dialogue317.txt compile dialogue text/dialogues/dialogue317.bin
	fe3-text text/dialogues/dialogue318.txt compile dialogue text/dialogues/dialogue318.bin
	fe3-text text/dialogues/dialogue319.txt compile dialogue text/dialogues/dialogue319.bin
	fe3-text text/dialogues/dialogue320.txt compile dialogue text/dialogues/dialogue320.bin
	fe3-text text/dialogues/dialogue321.txt compile dialogue text/dialogues/dialogue321.bin
	fe3-text text/dialogues/dialogue322.txt compile dialogue text/dialogues/dialogue322.bin
	fe3-text text/dialogues/dialogue323.txt compile dialogue text/dialogues/dialogue323.bin
	fe3-text text/dialogues/dialogue324.txt compile dialogue text/dialogues/dialogue324.bin
	fe3-text text/dialogues/dialogue325.txt compile dialogue text/dialogues/dialogue325.bin
	fe3-text text/dialogues/dialogue326.txt compile dialogue text/dialogues/dialogue326.bin
	fe3-text text/dialogues/dialogue327.txt compile dialogue text/dialogues/dialogue327.bin
	fe3-text text/dialogues/dialogue328.txt compile dialogue text/dialogues/dialogue328.bin
	fe3-text text/dialogues/dialogue329.txt compile dialogue text/dialogues/dialogue329.bin
	fe3-text text/dialogues/dialogue330.txt compile dialogue text/dialogues/dialogue330.bin
	fe3-text text/dialogues/dialogue331.txt compile dialogue text/dialogues/dialogue331.bin
	fe3-text text/dialogues/dialogue332.txt compile dialogue text/dialogues/dialogue332.bin
	fe3-text text/dialogues/dialogue333.txt compile dialogue text/dialogues/dialogue333.bin
	fe3-text text/dialogues/dialogue334.txt compile dialogue text/dialogues/dialogue334.bin
	fe3-text text/dialogues/dialogue335.txt compile dialogue text/dialogues/dialogue335.bin
	fe3-text text/dialogues/dialogue336.txt compile dialogue text/dialogues/dialogue336.bin
	fe3-text text/dialogues/dialogue337.txt compile dialogue text/dialogues/dialogue337.bin
	fe3-text text/dialogues/dialogue338.txt compile dialogue text/dialogues/dialogue338.bin
	fe3-text text/dialogues/dialogue339.txt compile dialogue text/dialogues/dialogue339.bin
	fe3-text text/dialogues/dialogue340.txt compile dialogue text/dialogues/dialogue340.bin
	fe3-text text/dialogues/dialogue341.txt compile dialogue text/dialogues/dialogue341.bin
	fe3-text text/dialogues/dialogue342.txt compile dialogue text/dialogues/dialogue342.bin
	fe3-text text/dialogues/dialogue343.txt compile dialogue text/dialogues/dialogue343.bin
	fe3-text text/dialogues/dialogue344.txt compile dialogue text/dialogues/dialogue344.bin
	fe3-text text/dialogues/dialogue345.txt compile dialogue text/dialogues/dialogue345.bin
	fe3-text text/dialogues/dialogue346.txt compile dialogue text/dialogues/dialogue346.bin
	fe3-text text/dialogues/dialogue347.txt compile dialogue text/dialogues/dialogue347.bin
	fe3-text text/dialogues/dialogue348.txt compile dialogue text/dialogues/dialogue348.bin
	fe3-text text/dialogues/dialogue349.txt compile dialogue text/dialogues/dialogue349.bin
	fe3-text text/dialogues/dialogue350.txt compile dialogue text/dialogues/dialogue350.bin
	fe3-text text/dialogues/dialogue351.txt compile dialogue text/dialogues/dialogue351.bin
	fe3-text text/dialogues/dialogue352.txt compile dialogue text/dialogues/dialogue352.bin
	fe3-text text/dialogues/dialogue353.txt compile dialogue text/dialogues/dialogue353.bin
	fe3-text text/dialogues/dialogue354.txt compile dialogue text/dialogues/dialogue354.bin
	fe3-text text/dialogues/dialogue355.txt compile dialogue text/dialogues/dialogue355.bin
	fe3-text text/dialogues/dialogue356.txt compile dialogue text/dialogues/dialogue356.bin
	fe3-text text/dialogues/dialogue357.txt compile dialogue text/dialogues/dialogue357.bin
	fe3-text text/dialogues/dialogue358.txt compile dialogue text/dialogues/dialogue358.bin
	fe3-text text/dialogues/dialogue359.txt compile dialogue text/dialogues/dialogue359.bin
	fe3-text text/dialogues/dialogue360.txt compile dialogue text/dialogues/dialogue360.bin
	fe3-text text/dialogues/dialogue361.txt compile dialogue text/dialogues/dialogue361.bin
	fe3-text text/dialogues/dialogue362.txt compile dialogue text/dialogues/dialogue362.bin
	fe3-text text/dialogues/dialogue363.txt compile dialogue text/dialogues/dialogue363.bin
	fe3-text text/dialogues/dialogue364.txt compile dialogue text/dialogues/dialogue364.bin
	fe3-text text/dialogues/dialogue365.txt compile dialogue text/dialogues/dialogue365.bin
	fe3-text text/dialogues/dialogue366.txt compile dialogue text/dialogues/dialogue366.bin
	fe3-text text/dialogues/dialogue367.txt compile dialogue text/dialogues/dialogue367.bin
	fe3-text text/dialogues/dialogue368.txt compile dialogue text/dialogues/dialogue368.bin
	fe3-text text/dialogues/dialogue369.txt compile dialogue text/dialogues/dialogue369.bin
	fe3-text text/dialogues/dialogue370.txt compile dialogue text/dialogues/dialogue370.bin
	fe3-text text/dialogues/dialogue371.txt compile dialogue text/dialogues/dialogue371.bin
	fe3-text text/dialogues/dialogue372.txt compile dialogue text/dialogues/dialogue372.bin
	fe3-text text/dialogues/dialogue373.txt compile dialogue text/dialogues/dialogue373.bin
	fe3-text text/dialogues/dialogue374.txt compile dialogue text/dialogues/dialogue374.bin
	fe3-text text/dialogues/dialogue375.txt compile dialogue text/dialogues/dialogue375.bin
	fe3-text text/dialogues/dialogue376.txt compile dialogue text/dialogues/dialogue376.bin
	fe3-text text/dialogues/dialogue377.txt compile dialogue text/dialogues/dialogue377.bin
	fe3-text text/dialogues/dialogue378.txt compile dialogue text/dialogues/dialogue378.bin
	fe3-text text/dialogues/dialogue379.txt compile dialogue text/dialogues/dialogue379.bin
	fe3-text text/dialogues/dialogue380.txt compile dialogue text/dialogues/dialogue380.bin
	fe3-text text/dialogues/dialogue381.txt compile dialogue text/dialogues/dialogue381.bin
	fe3-text text/dialogues/dialogue382.txt compile dialogue text/dialogues/dialogue382.bin
	fe3-text text/dialogues/dialogue383.txt compile dialogue text/dialogues/dialogue383.bin
	fe3-text text/dialogues/dialogue384.txt compile dialogue text/dialogues/dialogue384.bin
	fe3-text text/dialogues/dialogue385.txt compile dialogue text/dialogues/dialogue385.bin
	fe3-text text/dialogues/dialogue386.txt compile dialogue text/dialogues/dialogue386.bin
	fe3-text text/dialogues/dialogue387.txt compile dialogue text/dialogues/dialogue387.bin
	fe3-text text/dialogues/dialogue388.txt compile dialogue text/dialogues/dialogue388.bin
	fe3-text text/dialogues/dialogue389.txt compile dialogue text/dialogues/dialogue389.bin
	fe3-text text/dialogues/dialogue390.txt compile dialogue text/dialogues/dialogue390.bin
	fe3-text text/dialogues/dialogue391.txt compile dialogue text/dialogues/dialogue391.bin
	fe3-text text/dialogues/dialogue392.txt compile dialogue text/dialogues/dialogue392.bin
	fe3-text text/dialogues/dialogue393.txt compile dialogue text/dialogues/dialogue393.bin
	fe3-text text/dialogues/dialogue394.txt compile dialogue text/dialogues/dialogue394.bin
	fe3-text text/dialogues/dialogue395.txt compile dialogue text/dialogues/dialogue395.bin
	fe3-text text/dialogues/dialogue396.txt compile dialogue text/dialogues/dialogue396.bin
	fe3-text text/dialogues/dialogue397.txt compile dialogue text/dialogues/dialogue397.bin
	fe3-text text/dialogues/dialogue398.txt compile dialogue text/dialogues/dialogue398.bin
	fe3-text text/dialogues/dialogue399.txt compile dialogue text/dialogues/dialogue399.bin
	fe3-text text/dialogues/dialogue400.txt compile dialogue text/dialogues/dialogue400.bin
	fe3-text text/dialogues/dialogue401.txt compile dialogue text/dialogues/dialogue401.bin
	fe3-text text/dialogues/dialogue402.txt compile dialogue text/dialogues/dialogue402.bin
	fe3-text text/dialogues/dialogue403.txt compile dialogue text/dialogues/dialogue403.bin
	fe3-text text/dialogues/dialogue404.txt compile dialogue text/dialogues/dialogue404.bin
	fe3-text text/dialogues/dialogue405.txt compile dialogue text/dialogues/dialogue405.bin
	fe3-text text/dialogues/dialogue406.txt compile dialogue text/dialogues/dialogue406.bin
	fe3-text text/dialogues/dialogue407.txt compile dialogue text/dialogues/dialogue407.bin
	fe3-text text/dialogues/dialogue408.txt compile dialogue text/dialogues/dialogue408.bin
	fe3-text text/dialogues/dialogue409.txt compile dialogue text/dialogues/dialogue409.bin
	fe3-text text/dialogues/dialogue410.txt compile dialogue text/dialogues/dialogue410.bin
	fe3-text text/dialogues/dialogue411.txt compile dialogue text/dialogues/dialogue411.bin
	fe3-text text/dialogues/dialogue412.txt compile dialogue text/dialogues/dialogue412.bin
	fe3-text text/dialogues/dialogue413.txt compile dialogue text/dialogues/dialogue413.bin
	fe3-text text/dialogues/dialogue414.txt compile dialogue text/dialogues/dialogue414.bin
	fe3-text text/dialogues/dialogue415.txt compile dialogue text/dialogues/dialogue415.bin
	fe3-text text/dialogues/dialogue416.txt compile dialogue text/dialogues/dialogue416.bin
	fe3-text text/dialogues/dialogue417.txt compile dialogue text/dialogues/dialogue417.bin
	fe3-text text/dialogues/dialogue418.txt compile dialogue text/dialogues/dialogue418.bin
	fe3-text text/dialogues/dialogue419.txt compile dialogue text/dialogues/dialogue419.bin
	fe3-text text/dialogues/dialogue420.txt compile dialogue text/dialogues/dialogue420.bin
	fe3-text text/dialogues/dialogue421.txt compile dialogue text/dialogues/dialogue421.bin
	fe3-text text/dialogues/dialogue422.txt compile dialogue text/dialogues/dialogue422.bin
	fe3-text text/dialogues/dialogue423.txt compile dialogue text/dialogues/dialogue423.bin
	fe3-text text/dialogues/dialogue424.txt compile dialogue text/dialogues/dialogue424.bin
	fe3-text text/dialogues/dialogue425.txt compile dialogue text/dialogues/dialogue425.bin
	fe3-text text/dialogues/dialogue426.txt compile dialogue text/dialogues/dialogue426.bin
	fe3-text text/dialogues/dialogue427.txt compile dialogue text/dialogues/dialogue427.bin
	fe3-text text/dialogues/dialogue428.txt compile dialogue text/dialogues/dialogue428.bin
	fe3-text text/dialogues/dialogue429.txt compile dialogue text/dialogues/dialogue429.bin
	fe3-text text/dialogues/dialogue430.txt compile dialogue text/dialogues/dialogue430.bin
	fe3-text text/dialogues/dialogue431.txt compile dialogue text/dialogues/dialogue431.bin
	fe3-text text/dialogues/dialogue432.txt compile dialogue text/dialogues/dialogue432.bin
	fe3-text text/dialogues/dialogue433.txt compile dialogue text/dialogues/dialogue433.bin
	fe3-text text/dialogues/dialogue434.txt compile dialogue text/dialogues/dialogue434.bin
	fe3-text text/dialogues/dialogue435.txt compile dialogue text/dialogues/dialogue435.bin
	fe3-text text/dialogues/dialogue436.txt compile dialogue text/dialogues/dialogue436.bin
	fe3-text text/dialogues/dialogue437.txt compile dialogue text/dialogues/dialogue437.bin
	fe3-text text/dialogues/dialogue438.txt compile dialogue text/dialogues/dialogue438.bin
	fe3-text text/dialogues/dialogue439.txt compile dialogue text/dialogues/dialogue439.bin
	fe3-text text/dialogues/dialogue440.txt compile dialogue text/dialogues/dialogue440.bin
	fe3-text text/dialogues/dialogue441.txt compile dialogue text/dialogues/dialogue441.bin
	fe3-text text/dialogues/dialogue442.txt compile dialogue text/dialogues/dialogue442.bin
	fe3-text text/dialogues/dialogue443.txt compile dialogue text/dialogues/dialogue443.bin
	fe3-text text/dialogues/dialogue444.txt compile dialogue text/dialogues/dialogue444.bin
	fe3-text text/dialogues/dialogue445.txt compile dialogue text/dialogues/dialogue445.bin
	fe3-text text/dialogues/dialogue446.txt compile dialogue text/dialogues/dialogue446.bin
	fe3-text text/dialogues/dialogue447.txt compile dialogue text/dialogues/dialogue447.bin
	fe3-text text/dialogues/dialogue448.txt compile dialogue text/dialogues/dialogue448.bin
	fe3-text text/dialogues/dialogue449.txt compile dialogue text/dialogues/dialogue449.bin
	fe3-text text/dialogues/dialogue450.txt compile dialogue text/dialogues/dialogue450.bin
	fe3-text text/dialogues/dialogue451.txt compile dialogue text/dialogues/dialogue451.bin
	fe3-text text/dialogues/dialogue452.txt compile dialogue text/dialogues/dialogue452.bin
	fe3-text text/dialogues/dialogue453.txt compile dialogue text/dialogues/dialogue453.bin
	fe3-text text/dialogues/dialogue454.txt compile dialogue text/dialogues/dialogue454.bin
	fe3-text text/dialogues/dialogue455.txt compile dialogue text/dialogues/dialogue455.bin
	fe3-text text/dialogues/dialogue456.txt compile dialogue text/dialogues/dialogue456.bin
	fe3-text text/dialogues/dialogue457.txt compile dialogue text/dialogues/dialogue457.bin
	fe3-text text/dialogues/dialogue458.txt compile dialogue text/dialogues/dialogue458.bin
	fe3-text text/dialogues/dialogue459.txt compile dialogue text/dialogues/dialogue459.bin
	fe3-text text/dialogues/dialogue460.txt compile dialogue text/dialogues/dialogue460.bin
	fe3-text text/dialogues/dialogue461.txt compile dialogue text/dialogues/dialogue461.bin
	fe3-text text/dialogues/dialogue462.txt compile dialogue text/dialogues/dialogue462.bin
	fe3-text text/dialogues/dialogue463.txt compile dialogue text/dialogues/dialogue463.bin
	fe3-text text/dialogues/dialogue464.txt compile dialogue text/dialogues/dialogue464.bin
	fe3-text text/dialogues/dialogue465.txt compile dialogue text/dialogues/dialogue465.bin
	fe3-text text/dialogues/dialogue466.txt compile dialogue text/dialogues/dialogue466.bin
	fe3-text text/dialogues/dialogue467.txt compile dialogue text/dialogues/dialogue467.bin
	fe3-text text/dialogues/dialogue468.txt compile dialogue text/dialogues/dialogue468.bin
	fe3-text text/dialogues/dialogue469.txt compile dialogue text/dialogues/dialogue469.bin
	fe3-text text/dialogues/dialogue470.txt compile dialogue text/dialogues/dialogue470.bin
	fe3-text text/dialogues/dialogue471.txt compile dialogue text/dialogues/dialogue471.bin
	fe3-text text/dialogues/dialogue472.txt compile dialogue text/dialogues/dialogue472.bin
	fe3-text text/dialogues/dialogue473.txt compile dialogue text/dialogues/dialogue473.bin
	fe3-text text/dialogues/dialogue474.txt compile dialogue text/dialogues/dialogue474.bin
	fe3-text text/dialogues/dialogue475.txt compile dialogue text/dialogues/dialogue475.bin
	fe3-text text/dialogues/dialogue476.txt compile dialogue text/dialogues/dialogue476.bin
	fe3-text text/dialogues/dialogue477.txt compile dialogue text/dialogues/dialogue477.bin
	fe3-text text/dialogues/dialogue478.txt compile dialogue text/dialogues/dialogue478.bin
	fe3-text text/dialogues/dialogue479.txt compile dialogue text/dialogues/dialogue479.bin
	fe3-text text/dialogues/dialogue480.txt compile dialogue text/dialogues/dialogue480.bin
	fe3-text text/dialogues/dialogue481.txt compile dialogue text/dialogues/dialogue481.bin
	fe3-text text/dialogues/dialogue482.txt compile dialogue text/dialogues/dialogue482.bin
	fe3-text text/dialogues/dialogue483.txt compile dialogue text/dialogues/dialogue483.bin
	fe3-text text/dialogues/dialogue484.txt compile dialogue text/dialogues/dialogue484.bin
	fe3-text text/dialogues/dialogue485.txt compile dialogue text/dialogues/dialogue485.bin
	fe3-text text/dialogues/dialogue486.txt compile dialogue text/dialogues/dialogue486.bin
	fe3-text text/dialogues/dialogue487.txt compile dialogue text/dialogues/dialogue487.bin
	fe3-text text/dialogues/dialogue488.txt compile dialogue text/dialogues/dialogue488.bin
	fe3-text text/dialogues/dialogue489.txt compile dialogue text/dialogues/dialogue489.bin
	fe3-text text/dialogues/dialogue490.txt compile dialogue text/dialogues/dialogue490.bin
	fe3-text text/dialogues/dialogue491.txt compile dialogue text/dialogues/dialogue491.bin
	fe3-text text/dialogues/dialogue492.txt compile dialogue text/dialogues/dialogue492.bin
	fe3-text text/dialogues/dialogue493.txt compile dialogue text/dialogues/dialogue493.bin
	fe3-text text/dialogues/dialogue494.txt compile dialogue text/dialogues/dialogue494.bin
	fe3-text text/dialogues/dialogue495.txt compile dialogue text/dialogues/dialogue495.bin
	fe3-text text/dialogues/dialogue496.txt compile dialogue text/dialogues/dialogue496.bin
	fe3-text text/dialogues/dialogue497.txt compile dialogue text/dialogues/dialogue497.bin
	fe3-text text/dialogues/dialogue498.txt compile dialogue text/dialogues/dialogue498.bin
	fe3-text text/dialogues/dialogue499.txt compile dialogue text/dialogues/dialogue499.bin
	fe3-text text/dialogues/dialogue500.txt compile dialogue text/dialogues/dialogue500.bin
	fe3-text text/dialogues/dialogue501.txt compile dialogue text/dialogues/dialogue501.bin
	fe3-text text/dialogues/dialogue502.txt compile dialogue text/dialogues/dialogue502.bin
	fe3-text text/dialogues/dialogue503.txt compile dialogue text/dialogues/dialogue503.bin
	fe3-text text/dialogues/dialogue504.txt compile dialogue text/dialogues/dialogue504.bin
	fe3-text text/dialogues/dialogue505.txt compile dialogue text/dialogues/dialogue505.bin
	fe3-text text/dialogues/dialogue506.txt compile dialogue text/dialogues/dialogue506.bin
	fe3-text text/dialogues/dialogue507.txt compile dialogue text/dialogues/dialogue507.bin
	fe3-text text/dialogues/dialogue508.txt compile dialogue text/dialogues/dialogue508.bin
	fe3-text text/dialogues/dialogue509.txt compile dialogue text/dialogues/dialogue509.bin
	fe3-text text/dialogues/dialogue510.txt compile dialogue text/dialogues/dialogue510.bin
	fe3-text text/dialogues/dialogue511.txt compile dialogue text/dialogues/dialogue511.bin
	fe3-text text/dialogues/dialogue512.txt compile dialogue text/dialogues/dialogue512.bin
	fe3-text text/dialogues/dialogue513.txt compile dialogue text/dialogues/dialogue513.bin
	fe3-text text/dialogues/dialogue514.txt compile dialogue text/dialogues/dialogue514.bin
	fe3-text text/dialogues/dialogue515.txt compile dialogue text/dialogues/dialogue515.bin
	fe3-text text/dialogues/dialogue516.txt compile dialogue text/dialogues/dialogue516.bin
	fe3-text text/dialogues/dialogue517.txt compile dialogue text/dialogues/dialogue517.bin
	fe3-text text/dialogues/dialogue518.txt compile dialogue text/dialogues/dialogue518.bin
	fe3-text text/dialogues/dialogue519.txt compile dialogue text/dialogues/dialogue519.bin
	fe3-text text/dialogues/dialogue520.txt compile dialogue text/dialogues/dialogue520.bin

$(ROM).sfc: $(COBJ)
	$(LD) -d -v -S linkfile $(ROM).sfc
	@sha1sum -c checksum.sha1

clean:
	rm -f $(ROM).sfc $(COBJ)
