.BANK 85
.ORG $0000

.SECTION "Bank85" FORCE

.INCBIN "2A7E8B.bin" SKIP 373
PORTRAIT_VILLAGER_2ND_BALD_MAN:
.INCBIN "2A82FA.bin"
PORTRAIT_VILLAGER_BALD_MAN_2:
.INCBIN "2A87BC.bin"
PORTRAIT_VILLAGER_OLD_MAN:
.INCBIN "2A8C2B.bin"
PORTRAIT_VILLAGER_OLD_WOMAN:
.INCBIN "2A90F2.bin"
PORTRAIT_VILLAGER_UNCLE:
.INCBIN "2A9625.bin"
PORTRAIT_VILLAGER_AUNTIE:
.INCBIN "2A9B5F.bin"
PORTRAIT_VILLAGER_MALE:
.INCBIN "2AA0A1.bin"
PORTRAIT_VILLAGER_FEMALE:
.INCBIN "2AA59F.bin"
PORTRAIT_FIGHTMONGER:
.INCBIN "2AAB0A.bin"
PORTRAIT_ARMOURER:
.INCBIN "2AB0FC.bin"
PORTRAIT_VILLAGER_OLD_LADY_WITH_GLASSES:
.INCBIN "2AB69E.bin"
PORTRAIT_VENDOR:
.INCBIN "2ABB5F.bin"
PORTRAIT_SAVE_GIRL:
.INCBIN "2AC181.bin"
PORTRAIT_GIRL_UNKNOWN_SHOP:
.INCBIN "2AC726.bin"
PORTRAIT_GIRL_WITH_HOOD:
.INCBIN "2ACBB3.bin"
PORTRAIT_GUARD:
.INCBIN "2AD125.bin"
PORTRAIT_CECIL:
.INCBIN "2AD537.bin"
PORTRAIT_LUKE:
.INCBIN "2ADB51.bin"
PORTRAIT_RODERICK:
.INCBIN "2AE042.bin"
PORTRAIT_RYAN:
.INCBIN "2AE595.bin"
PORTRAIT_WARREN:
.INCBIN "2AEAE1.bin"
PORTRAIT_LUMEL:
.INCBIN "2AEFF9.bin"
PORTRAIT_LYKKE:
.INCBIN "2AF5B8.bin"
PORTRAIT_YULIYA:
.INCBIN "2AFB6A.bin" READ 1174

.ENDS
